# Site settings
title: MitnickEX Blog
SEOTitle: 博宇の小巢 | MitnickEX Blog
header-img: img/home-bg.jpg
email: shaoboyu0723@gmail.com
description: "关于测试与摄影 | 邵博宇，Test Engineer，Photographer | 这里是 @邵博宇 的个人博客，与你一起发现更大的世界。"
keyword: "邵博宇, 博宇, MitnickEX, mitnickshao, 博宇の小巢, MitnickEX Blog, 博客, 个人网站, 章亚男, 章亚男的老公"
url: "http://mitnickex.github.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# SNS settings
RSS: false
#weibo_username:     这个傻X就快要自杀了
zhihu_username:     邵博宇
github_username:    MitnickEX
#twitter_username:  MitnickEX
facebook_username:  Boyu.Shao
# linkedin_username:  firstname-lastname-idxxxx

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
